.TH x2godialog 1 "Nov 2018" "Version 4.1.0.4"
.SH NAME
x2godialog \- X2Go dialog tool.
.SH SYNOPSIS
.B x2godialog
.I "[options]"

.SH DESCRIPTION
\fBx2godialog\fR is a wrapper around nxdialog which is an a tool
to display graphical requestor windows which called used by x2goagent.

.SH OPTIONS
.TP
.B \--help
Lists all others options that are not listed here. For the complete
manpage please refer to the nxdialog manpage.

.SH FURTHER READINGS
Information on X2Go: https://wiki.x2go.org
.PP
Information on NX: https://github.com/ArcticaProject/nx-libs

.SH AUTHOR
This manual page was written by Ulrich Sibiller <uli42@gmx.de>.
